### ISSUE TITLE
Repo license

### ISSUE THREAD

**Issue by jasnow** [codeforatlanta/connector#41]
Can you please add a license to this repo so I can use it?
Thanks

Example: https://github.com/railstutorial/sample_app_rails_4/blob/master/LICENSE

Background Reference: http://opensource.org/licenses

**Comment by sb8244** [comment]
@luigi MIT cool?

**Comment by luigi** [comment]
@jasnow Thanks for bringing it up.

Added my preferred license, the BSD 3-Clause, since it has non-endorsement language:

926218c5319eb9323d7e94f78609681cbc452bf6

**Comment by jasnow** [comment]
Thanks
