### ISSUE TITLE
Ruby, Rails, and All gems out of date

### ISSUE THREAD

**Issue by alex-hall** [codeforatlanta/connector#55]
Like the title says, pretty much everything out of date.  Ruby 2.1 is not even supported anymore, 2.4.0 is the latest. Same with rails, 4.1 is not supported, only 5.0 and 4.2 are.

I can take a look at upgrading but I don't know what the limitation of CI/Heroku are for these things. Additionally, the move from 4.1 => 5 might be a not-so-small undertaking in my experience, it might make more sense to stay on ~4 for now.

**Comment by alex-hall** [comment]
Already found[ active rails bugs](https://github.com/rails/rails/issues/25125) with ruby 2.4.0. 

I think the Integer unification is going to take a while to fix for not only rails but every active record adapter.

Backing off to ruby 2.3.3 for now..

**Comment by luigi** [comment]
For now, let's target Ruby 2.3.x and Rails 4.2.x.

**Comment by alex-hall** [comment]
I have a green rake on a branch [here](https://github.com/alex-hall/connector/tree/update-gems-and-rails). Waiting on the first PR to be merged in then I'll create this one (otherwise you'd see the commit history from the first PR in this PR).

**Comment by sb8244** [comment]
I've done 4.1 to 4.2 and it's not that bad. I do agree to 5 is a big step.
The only thing I can think of is if we use respond with or not. I don't
think we do.

Heroku should handle the latest Ruby, so you probably won't need to worry
much about that upgrade. We're not doing anything particularly crazy in
this repo either.

**Comment by sb8244** [comment]
Good stuff in your WIP.

**Comment by alex-hall** [comment]
PR Submitted: #57
